name: mit_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  firebase_messaging: ^15.1.6
  firebase_database: ^11.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/